name: Retail Trends Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: [ main ]

permissions:
  contents: write

concurrency:
  group: retail-trends-bot
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot pipeline
        run: |
          python bot/fetch.py
          python bot/charts.py
          python bot/site_builder.py

      # Make sure our local branch includes any new remote commits
      - name: Sync with remote main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          # rebase preferred; fall back to merge if needed
          git pull --rebase origin main || git pull origin main

      - name: Debug: list outputs
        run: |
          echo "::group::assets"; ls -la assets || true; echo "::endgroup::"
          echo "::group::data";   ls -la data   || true; echo "::endgroup::"
          ls -la index.html || true

      - name: Commit updated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update homepage and assets"
          file_pattern: |
            index.html
            assets/**
            data/**
          branch: ${{ github.ref_name }}
