name: Retail Trends Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot pipeline
        run: |
          python bot/fetch.py
          python bot/site_builder.py

      - name: Commit site back to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A site data
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update site with latest headlines"
            git push
          fi
