name: Retail Trends Bot

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch headlines
        run: python bot/fetch.py

      - name: Build charts
        run: python bot/charts.py

      - name: Build site
        run: python bot/site_builder.py

      - name: Show outputs
        run: |
          ls -la
          ls -la assets || true
          ls -la data || true
          test -f index.html && echo "index.html exists"

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A index.html assets data
          git commit -m "Auto-update site" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin HEAD:main || git push --force-with-lease origin HEAD:main
