name: Retail Trends Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: retail-trends-bot
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot pipeline
        run: |
          set -e
          python bot/fetch.py
          python bot/charts.py
          python bot/site_builder.py

      - name: Sync with remote main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git rebase origin/main || git merge --no-edit origin/main

      - name: Commit updated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-update homepage and assets
          file_pattern: |
            index.html
            assets/**
            data/**
          branch: main
