name: Retail Trends Bot

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */12 * * *'   # every 12 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch headlines
        run: python bot/fetch.py

      - name: Build charts
        run: python bot/charts.py

      - name: Build site
        run: python bot/site_builder.py

      - name: Show outputs
        run: |
          echo "::group::Root"; ls -la; echo "::endgroup::"
          echo "::group::Assets"; ls -la assets || true; echo "::endgroup::"
          echo "::group::Data"; ls -la data || true; echo "::endgroup::"
          test -f index.html && echo "✓ index.html exists"
          test -f archive.html && echo "✓ archive.html exists"
          test -f data/summaries.json && echo "✓ summaries.json exists"

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A index.html archive.html assets data
          git commit -m "Auto-update site and archive" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin HEAD:main || git push --force-with-lease origin HEAD:main
