name: Retail Trends Bot

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */12 * * *'   # every 12 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Fetch articles
      - name: Fetch headlines
        run: python bot/fetch.py

      # 5) Quick preflight (so we see what's available)
      - name: Preflight
        run: |
          python -V
          echo "::group::data/"; ls -la data || true; echo "::endgroup::"
          if [ -f data/headlines.json ]; then
            python - <<'PY'
import json, pathlib
p = pathlib.Path("data/headlines.json")
print("headlines.json bytes:", p.stat().st_size)
j = json.loads(p.read_text(encoding="utf-8"))
print("articles:", len(j.get("articles", [])))
print("first:", (j.get("articles",[]) or [{}])[0])
PY
          fi

      # 6) Pull one hero image from today's articles (non-fatal if it fails)
      - name: Generate daily hero from article
        run: python bot/hero_from_articles.py
        continue-on-error: true

      # 7) Build charts & totals (must succeed)
      - name: Build charts
        run: python bot/charts.py

      # 8) Build site (index.html + archive.html)
      - name: Build site
        run: python bot/site_builder.py

      # 9) Debug artifacts (always upload so we can inspect if anything went wrong)
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            data/**
            assets/**
            index.html
            archive.html

      # 10) Commit & push generated files
      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A index.html archive.html assets data
          git commit -m "Auto-update site (hero + charts + archive)" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin HEAD:main || git push --force-with-lease origin HEAD:main